# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: "datee"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: "readyy"
    replace: |
      /draft
      /label ~"workflow::ready for review"

  - trigger: "labell"
    replace: /label ~"group::distribution" ~"section::enablement" ~"devops::systems"

  - trigger: "revieww"
    replace: |
      /label ~"workflow::in review"
      /assign_reviewer me

  - trigger: "approvee"
    replace: |
      /approve
      /assign_reviewer $|$

  - trigger: "detailss"
    replace: |
      <details>
      <summary>$|$</summary>


      </details>

  - trigger: "manifestt"
    replace: |
      apiVersion: apps.gitlab.com/v1beta1
      kind: GitLab
      metadata:
        name: gitlab
      spec:
        chart:
          version: "$|$"
        values:
          global:
            hosts:
              domain: mnielsen.k8s-ft.win
              externalIP: 35.227.120.173
          certmanager-issuer:
            email: mnielsen@gitlab.com

  - trigger: ":tu"
    replace: 👍
