[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[package]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[vagrant]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "bold cyan"
