gui:
  theme:
    lightTheme: false
  showIcons: true
  showFileTree: true # for rendering changes files in a tree format
  nerdFontsVersion: "3"
git:
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: "delta --paging=never"
os:
  editPreset: 'nvim'
keybinding:
  universal:
    quit: "q"
