k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: true
  logoless: true
  crumbsless: false
  readOnly: false
  noIcons: true
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 60
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: gke-mnielsen
  currentCluster: gke_cloud-native-182609_us-east1-b_mnielsen
  clusters:
    arn:aws:eks:us-east-2:474521830347:cluster/cloud-native:
      namespace:
        active: eks-helm-charts-win
        favorites:
        - eks-helm-charts-win
        - default
      view:
        active: po
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_cloud-native-182609_europe-west2-b_cloud-native:
      namespace:
        active: helm-charts-win
        favorites:
        - helm-charts-win
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_cloud-native-182609_us-east1-b_mnielsen:
      namespace:
        active: gitlab
        favorites:
        - gitlab
        - all
        - default
      view:
        active: chart
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_mnielsen-2e27a441_us-central1-c_geo-k8s-primary:
      namespace:
        active: gitlab
        favorites:
        - all
        - gitlab
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    gke_mnielsen-2e27a441_us-central1-c_geo-k8s-secondary:
      namespace:
        active: gitlab
        favorites:
        - gitlab
        - all
        - default
      view:
        active: pods
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-vagrant
