# $XDG_CONFIG_HOME/k9s/views.yml
views:
  # Alters the pod view column layout. Uses GVR as key
  v1/pods:
    columns:
      - NAME
      - READY
      - RESTARTS
      - STATUS
      - IP
      - AGE
