---
matches:
  - trigger: ;date
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: ;details
    replace: |
      <details>
      <summary>$|$</summary>


      </details>

  - trigger: ;tfcloud
    replace: |
      # Add on the same level as `required_providers`
      # and then run `terraform init -upgrade`
      cloud {
        organization = "prefect"
        workspaces {
          name = "<tfc workspace name here>"
        }
      }
