matches:
  - trigger: ;date
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: ;cng
    replace: https://gitlab.com/gitlab-org/build/cng

  - trigger: ;charts
    replace: https://gitlab.com/gitlab-org/charts/gitlab

  - trigger: ;operator
    replace: https://gitlab.com/gitlab-org/cloud-native/gitlab-operator

  - trigger: ;team-tasks
    replace: https://gitlab.com/gitlab-org/distribution/team-tasks/-/issues

  # https://gitlab.com/gitlab-org/distribution/team-tasks/-/blob/master/frequently-used-labels.md?ref_type=heads

  - trigger: ;labelui
    replace: |
      /assign me
      /label ~"pipeline failure::under investigation"

  - trigger: ;ready
    replace: |
      /ready
      /label ~"workflow::ready for review"

  - trigger: ;labels
    replace: /label ~"group::distribution" ~"section::core platform" ~"devops::systems"

  - trigger: ;review
    replace: |
      /label ~"workflow::in review"
      /assign_reviewer me

  - trigger: ;approve
    replace: |
      /approve
      /assign_reviewer $|$

  - trigger: ;detail
    replace: |
      <details>
      <summary>$|$</summary>


      </details>

  - trigger: ;retry
    replace: |
      @gitlab-bot retry_job $|$

  # https://docs.gitlab.com/ee/development/documentation/styleguide/#tabs
  - trigger: ;tabs
    replace: |
      ::Tabs

      :::TabTitle $|$

      :::TabTitle

      ::EndTabs

  - trigger: ;afaik
    replace: as far as I know

  - trigger: ;manifest
    replace: |
      apiVersion: apps.gitlab.com/v1beta1
      kind: GitLab
      metadata:
        name: gitlab
        namespace: gitlab-system
      spec:
        chart:
          version: "replaceme"
          values:
            global:
              appConfig:
                initialDefaults:
                  signupEnabled: false
              hosts:
                domain: gke.mnielsen-sandbox.com
                externalIP: 34.123.173.205
            certmanager-issuer:
              email: mnielsen@gitlab.com
