matches:
  - trigger: ;date
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"

  - trigger: ;detail
    replace: |
      <details>
      <summary>$|$</summary>


      </details>
