matches:
  - trigger: datee
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y/%m/%d"


  # https://gitlab.com/gitlab-org/distribution/team-tasks/-/blob/master/frequently-used-labels.md?ref_type=heads

  - trigger: ;labelui
    replace: |
      /assign me
      /label ~"pipeline failure::under investigation"

  - trigger: ;ready
    replace: |
      /ready
      /label ~"workflow::ready for review"

  - trigger: ;labels
    replace: /label ~"group::distribution" ~"section::enablement" ~"devops::systems"

  - trigger: ;review
    replace: |
      /label ~"workflow::in review"
      /assign_reviewer me

  - trigger: ;approve
    replace: |
      /approve
      /assign_reviewer $|$

  - trigger: ;detail
    replace: |
      <details>
      <summary>$|$</summary>


      </details>

  - trigger: ;manifest
    replace: |
      apiVersion: apps.gitlab.com/v1beta1
      kind: GitLab
      metadata:
        name: gitlab
        namespace: gitlab-system
      spec:
        chart:
          version: "replaceme"
          values:
            global:
              appConfig:
                initialDefaults:
                  signupEnabled: false
              hosts:
                domain: gke.mnielsen-sandbox.com
                externalIP: 34.123.173.205
            certmanager-issuer:
              email: mnielsen@gitlab.com
