format = """
$kubernetes$directory$git_branch$git_status$git_state$custom
$character
"""

[fill]
disabled = true
symbol = '-'
style = 'gray'

[direnv]
disabled = true

[jobs]
disabled = true

[line_break]
disabled = true

[package]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false
format = '\([$context:$namespace](blue)\) '
# format = '\([$context:$namespace](blue)\) ' 

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "$cluster"

[terraform]
disabled = true

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
truncation_length = 2
truncate_to_repo = false
style = "purple"
format = "[‚ò∏ $path]($style) "

[git_status]
ahead = "‚á°${count}"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind)]($style) "
diverged = "‚áï‚á°${ahead_count}‚á£${behind_count}"
behind = "‚á£${count}"
style = "cyan"

[git_branch]
symbol = "Œª "
format = "on [$symbol$branch]($style) "
style = "green"
ignore_branches = []

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'

[custom.containers]
command = 'docker ps -aq | wc -l'
when = ''' test $(docker ps -aq | wc -l) -ne 0 '''
format = ' üê≥ [$output]($style)'
