format = """
$directory$git_branch$git_status$git_state$kubernetes$cmd_duration$fill
$character
"""

[fill]
disabled = true
symbol = '-'
style = 'gray'

[line_break]
disabled = false

[package]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[vagrant]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false
format = 'in [☸ $context:$namespace](blue) '

# # -----
# # https://starship.rs/presets/pure-preset.html
# # -----
[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
truncation_length = 8
truncate_to_repo = false
style = "blue"

[git_status]
ahead = "⇡${count}"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style) "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "cyan"
stashed = "≡"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "green"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'
