format = """
$directory$git_branch$git_status$git_state$kubernetes$cmd_duration$fill
$character
"""

palette = "catppuccin_latte"

[fill]
symbol = '-'
style = 'gray'

[line_break]
disabled = false

[package]
disabled = true

[helm]
disabled = true

[ruby]
disabled = true

[golang]
disabled = true

[hostname]
disabled = true

[username]
disabled = true

[gcloud]
disabled = true

[vagrant]
disabled = true

[python]
disabled = true

[nodejs]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = false
format = 'in [☸ $context:$namespace](blue) '

# # -----
# # https://starship.rs/presets/pure-preset.html
# # -----
[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'

[directory]
truncation_length = 8
truncate_to_repo = false
style = "yellow"

[git_status]
ahead = "⇡${count}"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style) "
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
style = "cyan"
stashed = "≡"

[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
style = "green"

[git_state]
format = '\([$state($progress_current/$progress_total)]($style)\)'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
