[tools]
aws = "latest"
actionlint = "1.7.1"
flux2 = "2.5.1"
gcloud = "517.0.0"
golang = "system"
helm = "system"
istioctl = "latest"
rust = "latest" # for uvx
terraform = "1.10.5"
python = "3.12"
updatecli = "latest"
stylua = "latest"
uv = "latest" # for python

[settings]
experimental = true

# config files with these prefixes will be trusted by default
trusted_config_paths = [
  '~/code',
]
