[tools]
actionlint = "1.7.1"
flux2 = "2.5.1"
gcloud = "517.0.0"
golang = "latest"
helm = "latest"
istioctl = "latest"
terraform = "1.10.5"
updatecli = "latest"
stylua = "latest"
# Python
python = "3.12"
uv = "latest" # for python
rust = "latest" # for uvx
aws = "latest" # specify after 'python' to control PATH
ruff = "latest"

[settings]
experimental = true

# config files with these prefixes will be trusted by default
trusted_config_paths = [
  '~/code',
]
