[tools]
actionlint = '1.7.1'
golang = 'system'
helm = 'system'
terraform = '1.9.8'


[settings]

# Support new syntax for resolving tools
experimental = true

# config files with these prefixes will be trusted by default
trusted_config_paths = [
  '~/code',
]
