[tools]
actionlint = '1.7.1'
golang = 'system'
helm = 'system'
rust = 'latest' # for uvx
terraform = "1.10.5"
uv = 'latest' # for python

[settings]

# Support new syntax for resolving tools
experimental = true

# config files with these prefixes will be trusted by default
trusted_config_paths = [
  '~/code',
]
