[tools]
golang = "latest"
istioctl = "latest"
terraform = "1.10.5"
updatecli = "latest"
kubectl = "1.31.1"

stylua = "latest"

# Python
python = "3.12"
uv = "latest" # for python
rust = "latest" # for uvx
aws = "latest" # specify after 'python' to control PATH
ruff = "latest"

# Go
"go:go.xrstf.de/stalk" = "latest" # https://codeberg.org/xrstf/stalk

[settings]
experimental = true

trusted_config_paths = [
  '~/src',
]
idiomatic_version_file_enable_tools = ["node"]
